postgres:
  image: "postgres:latest"
  volumes_from:
    - data
  ports:
    - 5432
#  env_file: .env
#  environment:
#    - POSTGRES_PASSWORD=Ref_ApP
#    - POSTGRES_USER=api
#    - POSTGRES_PORT=5432

data:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL and Bundler'
  volumes:
    - /var/lib/postgresql/data

api:
  build: .
  ports:
    - "3000:3000"
  links:
    - postgres
  volumes:
    - .:/home/api/
    - /home/api/node_modules
  volumes_from:
    - data
#  env_file: .env
#  environment:
#    - API_HOST=0.0.0.0
#    - API_PORT=3000
#    - SECRET_TOKEN=op_devtoken

