postgres:
  image: "postgres:latest"
  volumes_from:
    - data
  ports:
    - 5432
  environment:
    POSTGRES_PASSWORD: Ref_ApP
    POSTGRES_USER: api
    POSTGRES_PORT: 5432

data:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - /var/lib/postgresql/data

redis:
  image: redis

api:
  build: .
  ports:
    - "3000:3000"
  links:
    - postgres
    - redis
  volumes:
    - .:/home/api/
    - /home/api/node_modules
  volumes_from:
    - data
  environment:
    HOST: 0.0.0.0
    PORT: 3000
    SECRET_TOKEN: au_devtoken
