version: '2'
services:
  postgres:
    image: "postgres:9.5.2"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432
    container_name: autorenter-postgres
  redis:
    image: "redis:3.0.7"
    volumes:
      - redis-data:/var/lib/redis
    container_name: autorenter-redis
  api:
    build: .
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/home/api/
volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
